// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dist_by_closeness
NumericMatrix dist_by_closeness(NumericMatrix mat);
RcppExport SEXP _EnrichedHeatmap_dist_by_closeness(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(dist_by_closeness(mat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_EnrichedHeatmap_dist_by_closeness", (DL_FUNC) &_EnrichedHeatmap_dist_by_closeness, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_EnrichedHeatmap(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
