# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393


# == title
# Distance by closeness
#
# == param
# -mat a numeric matrix where the distance is calculated by rows
#
# == details
# The distance is calcuated by the relative closeness in the matrix.
# For two rows in the matrix, assume x_1, x_2, x_{n_1} and
# y_1, y_2, ... y_{n_2} are the column index where there are non-zero values, 
# the distance based on the closeness is calculated as:
#
# d_closeness = sum_{i,j}(|x_i - y_j|) / (n_1*n_2)
#
# == value
# A `stats::dist` object
#
# == author
# Zuguang Gu <z.gu@dkfz.de>
#
# == example
# x1 = c(0, 0, 0, 0, 1, 1, 1, 0, 0, 0)
# x2 = c(0, 0, 0, 1, 1, 1, 0, 0, 0, 0)
# x3 = c(0, 0, 1, 1, 1, 0, 0, 0, 0, 0)
# m = rbind(x1, x2, x3)
# dist_by_closeness(m)
#
dist_by_closeness = function(mat) {
    as.dist(.Call("_EnrichedHeatmap_dist_by_closeness", mat))
}

